-- =====================================================================
-- handle_new_user() -- fix a real gap in the unique_violation retry
-- loop: username was never actually retried.
--
-- The placeholder username has always been a deterministic slice of
-- new.id ('tickler_' || substr(new.id::text, 1, 8)) -- 8 hex characters,
-- the same 32-bit entropy budget migration 0028 already flagged for
-- referral_code. 0028 added a retry-on-unique_violation loop, but it
-- only ever regenerates v_referral_code each attempt -- username stays
-- fixed (it's derived from new.id, which doesn't change across
-- retries), so a collision actually caused by the username constraint
-- (profiles.username is unique, 0001) reproduces identically on every
-- one of the 5 attempts and still hard-fails the signup after them,
-- exactly as if the loop weren't there at all. Confirmed via birthday-
-- paradox math (2^32 space): ~1.2% cumulative collision probability by
-- 10k signups, 50% by ~77k -- not a scale this app's own referral
-- growth mechanic is trying to avoid.
--
-- Fix: username is now generated by random_placeholder_username()
-- (same shape as random_founding_member_referral_code, minus the
-- uppercasing -- referral codes are uppercased because a person reads
-- and types them; a placeholder username is neither, so it stays
-- lowercase to match every existing 'tickler_xxxxxxxx' row already in
-- the table) and regenerated fresh on every retry attempt, so a
-- username-caused collision is now a genuinely independent draw each
-- time, exactly like referral_code already was.
-- =====================================================================

create or replace function public.random_placeholder_username()
returns text
language sql
as $$
  select 'tickler_' || substr(md5(random()::text || clock_timestamp()::text), 1, 8);
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
as $$
declare
  v_username      text;
  v_referral_code text;
  v_attempts      integer := 0;
begin
  loop
    v_attempts := v_attempts + 1;
    v_username := public.random_placeholder_username();
    v_referral_code := public.random_founding_member_referral_code();
    begin
      insert into public.profiles (id, username, referral_code)
      values (new.id, v_username, v_referral_code);
      exit;
    exception when unique_violation then
      -- Both username and referral_code are now fresh, independent
      -- draws each attempt -- whichever constraint actually collided,
      -- retrying has a real chance of succeeding, not just a wasted
      -- attempt before the same guaranteed failure.
      if v_attempts >= 5 then
        raise;
      end if;
    end;
  end loop;

  insert into public.founding_member_enrollment (user_id)
  values (new.id);

  return new;
end;
$$;
